# Test Pipeline for testing Microsoft Test Results Upload

trigger:
- none

pool:
  name: MSTroubleShooting

variables:
#  - name: agent.disablelogplugin
#    value: true
  - name: system.debug
    value: true

steps:
- task: Bash@3
  displayName: 'Bash Test'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
#- task: Maven@4
#  displayName: 'Testing with the base pom.xml'
#  inputs:
#    mavenPOMFile: 'pom.xml'
#    publishJUnitResults: false
#    javaHomeOption: JDKVersion
#    mavenVersionOption: Default
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

#- task: PublishTestResults@2
#  displayName: 'Publish Test Results **/TEST-*.xml'
#  retryCountOnTaskFailure: 